name = "sign"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = "build/client"

[site]
bucket = "./build/client"

[build.upload]
format = "service-worker"

[[functions]]
pattern = "/*"
worker = "functions/_worker.js"
