[build]
command = "npm run build"
pages_build_output_dir = "./build/client"

[site]
bucket = "./build/client"
name = "sign"
main = "./build/client/index.js"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]

[env.production]
pages_build_output_dir = "./build/client"
name = "sign-prod"

[env.staging]
name = "sign-staging"
