[build]
command = "npm run build"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[build.upload]
format = "service-worker"

[site]
bucket = "./build/client"
name = "sign"

[env.production]
name = "sign-prod"

[env.staging]
name = "sign-staging"
