name = "sign"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./build/client"

[[functions]]
pattern = "/*"
directory = "./functions"
