name = "sign"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "build/client"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[pages]
pages_build_output_dir = "build/client"
